services:

  firefly:
    image: fireflyiii/core:latest
    container_name: firefly
    restart: unless-stopped
    volumes:
      - ./firefly_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - "8200:8080"
    depends_on:
      - db
      
  db:
    image: mariadb:latest   
    container_name: firefly-db
    restart: unless-stopped
    env_file: .db.env
#    environment:
#      - MYSQL_RANDOM_ROOT_PASSWORD=yes
#      - MYSQL_USER=firefly
#      - MYSQL_PASSWORD=firefly_password
#      - MYSQL_DATABASE=firefly
    volumes:
      - ./firefly_db:/var/lib/mysql

   
